//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyofPlants
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Designers 
    {        
        public int Id { get; set; }
        public string LFM { get; set; }
        public int Phone { get; set; }
        public string Address { get; set; }
        public string Education { get; set; }
        public string Institution_name { get; set; }

        
    }
   
}
