//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyofPlants
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plants
    {
        public Plants()
        {
            this.RegimeWatering = new HashSet<RegimeWatering>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date_planting { get; set; }
        public int Plant_age { get; set; }
        public string Sort_plant { get; set; }
        public Nullable<int> Id_worker { get; set; }
    
        public virtual Workers Workers { get; set; }
        public virtual ICollection<RegimeWatering> RegimeWatering { get; set; }
    }
}
