//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyofPlants
{
    using System;
    using System.ComponentModel;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class planting_parksEntities : DbContext
    {
        private static planting_parksEntities _context;   ///Контекст данных
        public planting_parksEntities()
            : base("name=planting_parksEntities")
        {
        }

        public static planting_parksEntities GetContext()     ///Метод GetContext, позволяющий возвращать данные из базы данных
        {
            if (_context == null)       ///Если контекст пуст
                _context = new planting_parksEntities();      ///Создание нового экземпляра контекста
            return _context;        ///Возврат контекста
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }        

        public DbSet<Designers> Designers { get; set; }
        public DbSet<Plants> Plants { get; set; }
        public DbSet<RegimeWatering> RegimeWatering { get; set; }
        public DbSet<Services> Services { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Workers> Workers { get; set; }
    }
}
