//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyofPlants
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegimeWatering
    {
        public RegimeWatering()
        {
            this.Workers = new HashSet<Workers>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date_watering { get; set; }
        public int Amount_water { get; set; }
        public int Plant_id { get; set; }
    
        public virtual Plants Plants { get; set; }
        public virtual ICollection<Workers> Workers { get; set; }
    }
}
