//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyofPlants
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public Workers()
        {
            this.Plants = new HashSet<Plants>();
            this.Services = new HashSet<Services>();
        }
    
        public int Id { get; set; }
        public string LFM { get; set; }
        public int Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> Watering_id { get; set; }
    
        public virtual ICollection<Plants> Plants { get; set; }
        public virtual RegimeWatering RegimeWatering { get; set; }
        public virtual ICollection<Services> Services { get; set; }
    }
}
